# This file configures Netlify for your project.

[build]
  # The directory to publish to Netlify (where your index.html, CSS, and JS are)
  publish = "."

  # The directory where your Netlify Functions are located
  functions = "netlify/functions"

# Redirects (optional, but good for SPAs if you add client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # This redirect ensures that all requests (e.g., direct links to /some-game-id)
  # are served by index.html, allowing your JavaScript to handle the routing
  # and read the gameId from the URL.
